classes: {
    business-actor: {
        icon: ./symbols/business-actor.svg {near: top-right}
        style: {
            fill: "#FFFFBD"
            stroke-width: 1
            shadow: true
            border-radius: 5
          }
    }
}

