classes: {

    application-interface: {
        icon: ./symbols/application-interface.svg
        style: {
          fill: "#99ffff"
          stroke-width: 1
          shadow: true
          border-radius: 5
        }
        
      }

    business-actor: {
        icon: ./symbols/business-actor.svg {near: top-right}
        style: {
            fill: "#ffff99"
            stroke-width: 1
            shadow: true
            border-radius: 5
          }
    }
}

