classes: {
  application-collaboration: {
    icon: ./symbols/application-collaboration.svg
    style: {
      fill: "#99ffff"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
  application-component: {
    icon: ./symbols/application-component.svg
    style: {
      fill: "#99ffff"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
  application-event: {
    icon: ./symbols/application-event.svg
    style: {
      fill: "#99ffff"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
  application-function: {
    icon: ./symbols/application-function.svg
    style: {
      fill: "#99ffff"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
  application-interaction: {
    icon: ./symbols/application-interaction.svg
    style: {
      fill: "#99ffff"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
  application-interface: {
    icon: ./symbols/application-interface.svg
    style: {
      fill: "#99ffff"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
  application-process: {
    icon: ./symbols/application-process.svg
    style: {
      fill: "#99ffff"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
  application-service: {
    icon: ./symbols/application-service.svg
    style: {
      fill: "#99ffff"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
  business-actor: {
    icon: ./symbols/business-actor.svg {near: top-right}
    style: {
      fill: "#ffff99"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }
}
